version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
    ports:
      - "35432:5432"
  localstack:
    container_name: "LocalStack-Demo"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566" # Edge Port
      - "4569:4569" # Dynamo DB Port
      - "4571:4571" # Elasticsearch Port
      - "4572:4572" # S3 Port
      - "4574:4574" # Lambda Port
      - "8080:8080" # Web-UI Port