server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/social_network

  thymeleaf:
    check-template-location: false